### ISSUE TITLE
Successful Message Received showing as errors

### ISSUE THREAD

**Issue by ryanbuckner** [Ghawken/iMessagePlugin#12]
I have a process that sends an iMessage and asks for a response, then processes that response. The process is working properly, but for some reason the responses are logged twice, and as errors.  

```
Aug 3, 2023 at 11:26:31 AM
   iMessage Plugin Error           iMessage Received from Buddy(s):  Buddy(s) Handle Below:
   iMessage Plugin Error           buddyname@gmail.com
   iMessage Plugin Error           iMessage Received from Buddy(s):  Buddy(s) Handle Below:
   iMessage Plugin Error           buddyname@gmail.com
```

**Comment by Ghawken** [comment]
Hi
This is the number one asked question!

I think you must be on a earlier version as well?  I may be a bit behind in the store - adds chatGPT as to the imessage replies - and was waiting for this to be finalised.  Although the chatGPT via imessage is getting a lot of usage in our household.

Coming back to your error message:
This is because you have selected show buddy Handles or some similar wording in the pluginConfig box.
It is used to check you know what the buddy handle is - as sometimes email, other times phone numbers etc.

Uncheck it and will go away.

**Comment by ryanbuckner** [comment]
right. I'm on v0.6.2 - I'll upgrade and deselect
